version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: vote
      MYSQL_USER: ultraman
      MYSQL_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
      - ./vote.sql:/docker-entrypoint-initdb.d/vote.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  app:
    build: .
    container_name: vote-system-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
