INSERT IGNORE INTO roles(name) VALUES('ROLE_USER');
INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PIRATES');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PIRATE_KING');
INSERT IGNORE INTO roles(name) VALUES('ROLE_NAVY');
